"""
Django settings for secinbots project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

ENVIRONMENT = os.environ["ENV"]

if ENVIRONMENT == "Prod":
    print("Using Prod Settings...") # These are set server side

    # Django Platform Key
    SECRET_KEY = os.environ["SECRET_KEY"]

    # Debug Mode
    DEBUG = False
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_HSTS_SECONDS = 60
    
    # Encrypted Fields Config
    SECURED_FIELDS_KEY = os.environ["SECURED_FIELDS_KEY"]
    SECURED_FIELDS_HASH_SALT = os.environ["SECURED_FIELDS_HASH_SALT"]

    # CSP Config
    CSP_DEFAULT_SRC = ("'self'")
    CSP_SCRIPT_SRC = ("'sha256-gu+jn7u1lu7JsiXQo40kBQofiYKwsXcp2Z4zoYhKQFk='", 
        "cdn.jsdelivr.net",
        "'self'",
        )
    CSP_CONNECT_SRC = ("'self'")
    CSP_IMG_SRC = ("'self'", "data:")
    CSP_FONT_SRC = ("'self'")
    CSP_STYLE_SRC = ("'sha256-gu+jn7u1lu7JsiXQo40kBQofiYKwsXcp2Z4zoYhKQFk='", 
        "cdn.jsdelivr.net",
        "'self'",
        )
    CSP_URI_SRC = ("'none'")
    CSP_UPGRADE_INSECURE_REQUESTS = True
    CSP_FORM_ACTION = ("'self'")
    CSP_FRAME_ANCESTORS=("'none'")
    CSP_WORKER_SRC=("'none'")

    # CORS Config
    CORS_ALLOW_ALL_ORIGINS=False
    CORS_ALLOWED_ORIGINS = [
        "https://secinbots.herokuapp.com",
    ]
    
    # Allowed Domains
    ALLOWED_HOSTS = ['secinbots.herokuapp.com']

    # SMTP Server Config
    EMAIL_HOST = "smtp.mailgun.org"
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.environ.get("MAILGUN_SMTP_LOGIN")
    EMAIL_HOST_PASSWORD = os.environ.get("MAILGUN_SMTP_PASSWORD")
    EMAIL_USE_TLS = True

    # Password validation
    # https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
            'OPTIONS': {
            'min_length': 12,
            }
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]

    # Database
    # https://docs.djangoproject.com/en/3.0/ref/settings/#databases
    MAX_CONN_AGE = 600
    DATABASES = {}
    DATABASES["default"] = dj_database_url.config(conn_max_age=MAX_CONN_AGE, ssl_require=True)

else:
    print("Using Dev Settings...")  # These are set local side

    SECRET_KEY = 'ph(m2(adnduebqe^nsb^kq=40+$#fex1$+u9p!if(6*+hzu2_l'
    DEBUG = True
    SECURED_FIELDS_KEY = 'TtY8MAeXuhdKDd1HfGUwim-vQ8H7fXyRQ9J8pTi_-lg='
    SECURED_FIELDS_HASH_SALT = '500d492e'  # optional
    
    # CSP Config
    #         "'strict-dynamic'",
    CSP_DEFAULT_SRC = ("'self'")
    CSP_SCRIPT_SRC = ("'sha256-gu+jn7u1lu7JsiXQo40kBQofiYKwsXcp2Z4zoYhKQFk='", 
        "cdn.jsdelivr.net",
        "'self'",
        )
    CSP_CONNECT_SRC = ("'self'")
    CSP_IMG_SRC = ("'self'", "data:")
    CSP_FONT_SRC = ("'self'")
    CSP_STYLE_SRC = ("'sha256-gu+jn7u1lu7JsiXQo40kBQofiYKwsXcp2Z4zoYhKQFk='", 
        "cdn.jsdelivr.net",
        "'self'",
        )
    CSP_URI_SRC = ("'none'")
    CSP_UPGRADE_INSECURE_REQUESTS = True
    CSP_FORM_ACTION = ("'self'")
    CSP_FRAME_ANCESTORS=("'none'")
    CSP_WORKER_SRC=("'none'")
    CSP_REPORT_ONLY=True
 
    ALLOWED_HOSTS = ['localhost',
                    '127.0.0.1']
    # python -m smtpd -n -c DebuggingServer localhost:1025
    EMAIL_HOST = "localhost"
    EMAIL_PORT = 1025
    AUTH_PASSWORD_VALIDATORS = []
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'secinbots.v1',
            'USER': 'hectorespinoza',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# Defining auto private keys fields
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

INSTALLED_APPS = [
    'messagex',
    'secured_fields',
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'secinbots.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'secinbots.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

TIME_ZONE = 'America/Los_Angeles' 

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# Fix for collecstatic
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_URL = '/account/login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'index'