# Generated by Django 3.0.4 on 2022-08-24 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=256, verbose_name='Message Text')),
                ('status', models.CharField(choices=[('UR', 'Unread'), ('RD', 'Read'), ('MD', 'Modified'), ('DL', 'Deleted')], default='UNREAD', max_length=2, verbose_name='Message Status')),
                ('timestamp', models.DateTimeField(default=datetime.date.today, verbose_name='Message Timestamp')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Message Recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Message Sender')),
            ],
        ),
    ]
