# Generated by Django 3.0.4 on 2022-08-24 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagex', '0002_auto_20220824_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Messagex',
        ),
    ]
