# Generated by Django 3.0.4 on 2022-08-24 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messagex', '0003_auto_20220824_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagex',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message Timestamp'),
        ),
    ]
