# Generated by Django 4.1.1 on 2022-09-19 22:57

from django.db import migrations, models
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("messagex", "0004_auto_20220824_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagex",
            name="etext",
            field=secured_fields.fields.EncryptedCharField(
                default="", max_length=256, verbose_name="Encrypted Message Text"
            ),
        ),
        migrations.AddField(
            model_name="messagex",
            name="subject",
            field=models.CharField(
                default="", max_length=50, verbose_name="Message Subject"
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="status",
            field=models.CharField(
                choices=[
                    ("UR", "Unread"),
                    ("RD", "Read"),
                    ("MD", "Modified"),
                    ("DL", "Deleted"),
                ],
                default="UR",
                max_length=2,
                verbose_name="Message Status",
            ),
        ),
    ]
