# Generated by Django 4.1.1 on 2022-09-21 06:03

from django.db import migrations
import django.utils.timezone
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("messagex", "0006_rename_timestamp_messagex_time_stamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagex",
            name="etext",
        ),
        migrations.RemoveField(
            model_name="messagex",
            name="status",
        ),
        migrations.AlterField(
            model_name="messagex",
            name="subject",
            field=secured_fields.fields.EncryptedCharField(
                default="", max_length=256, verbose_name="Message Subject"
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="text",
            field=secured_fields.fields.EncryptedCharField(
                default="", max_length=256, verbose_name="Message Text"
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="time_stamp",
            field=secured_fields.fields.EncryptedDateTimeField(
                default=django.utils.timezone.now, verbose_name="Message Timestamp"
            ),
        ),
    ]
