# Generated by Django 4.1.1 on 2022-09-26 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messagex", "0007_remove_messagex_etext_remove_messagex_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagex",
            name="text_area",
            field=secured_fields.fields.EncryptedTextField(
                default="", max_length=512, verbose_name="Message:"
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient:",
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender:",
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="subject",
            field=secured_fields.fields.EncryptedCharField(
                default="", max_length=256, verbose_name="Subject:"
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="text",
            field=secured_fields.fields.EncryptedCharField(
                default="", max_length=256, verbose_name="Message:"
            ),
        ),
        migrations.AlterField(
            model_name="messagex",
            name="time_stamp",
            field=secured_fields.fields.EncryptedDateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp:"
            ),
        ),
    ]
