# Generated by Django 4.1.1 on 2022-09-26 07:30

from django.db import migrations
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("messagex", "0008_messagex_text_area_alter_messagex_recipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagex",
            name="text_area",
        ),
        migrations.AlterField(
            model_name="messagex",
            name="text",
            field=secured_fields.fields.EncryptedTextField(
                default="", max_length=512, verbose_name="Message:"
            ),
        ),
    ]
