# Generated by Django 4.1.1 on 2022-09-27 04:28

from django.db import migrations
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("messagex", "0009_remove_messagex_text_area_alter_messagex_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagex",
            name="subject",
            field=secured_fields.fields.EncryptedCharField(
                default="", max_length=100, verbose_name="Subject:"
            ),
        ),
    ]
